apiVersion: v2
name: cas-data-warehouse
description: A Helm chart to deploy the CAS Data Warehouse

type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: cas-postgres-cluster
    version: 1.1.3
    repository: https://bcgov.github.io/cas-postgres
    alias: pg
  - name: cas-airflow-dag-trigger
    version: 1.0.20
    repository: https://bcgov.github.io/cas-airflow
    alias: download-cas-data-warehouse-dags
  - name: cas-airflow-dag-trigger
    version: 1.0.20
    repository: https://bcgov.github.io/cas-airflow
    alias: import-data-sources-dag
    