apiVersion: v2
name: cas-data-warehouse
description: A Helm chart to deploy the CAS Data Warehouse

type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: cas-postgres-cluster
    version: 1.1.3
    repository: https://bcgov.github.io/cas-postgres
    alias: pg
    