# This policy could be with the CIIP helm chart instead.

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name:  {{ template "cas-data-warehouse.fullname" . }}-metabase-access
  labels:
{{ include "cas-data-warehouse.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      release: cas-ciip-portal
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: cas-data-warehouse
  policyTypes:
    - Ingress

